name       : jack-audio-connection-kit
version    : 0.125.0
release    : 7
source     :
    - http://jackaudio.org/downloads/jack-audio-connection-kit-0.125.0.tar.gz : 3517b5bff82139a76b2b66fe2fd9a3b34b6e594c184f95a988524c575b11d444
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.audio
summary    : JACK is a professional sound server daemon
description: |
    JACK is a professional sound server daemon that provides real-time,
    low-latency connections for both audio and MIDI data between applications
    that implement its API.
emul32     : yes
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(celt)
    - pkgconfig32(portaudio-2.0)
    - pkgconfig32(samplerate)
    - pkgconfig32(sndfile)
    - db5-32bit-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/limits.conf $installdir/etc/security/limits.d/90-jack.conf
