name       : jack-audio-connection-kit
version    : 1.9.14
release    : 11
source     :
    - https://github.com/jackaudio/jack2/archive/v1.9.14.tar.gz : a20a32366780c0061fd58fbb5f09e514ea9b7ce6e53b080a44b11a558a83217c
homepage   : https://jackaudio.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.audio
summary    : JACK2 low-latency audio server for multi-core machines.
description: |
    JACK2 is a C++ version of the JACK low-latency audio server for multi-core machines. It is a new implementation of the JACK server core features that aims at removing some limitations of the JACK1 design. The activation system has been changed for a data flow model and lock-free programming techniques for graph access have been used to have a more dynamic and robust system.
emul32     : yes
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(celt)
    - pkgconfig32(dbus-1)
    - pkgconfig32(eigen3)
    - pkgconfig32(expat)
    - pkgconfig32(libgcrypt)
    - pkgconfig32(liblzma)
    - pkgconfig32(opus)
    - pkgconfig32(portaudio-2.0)
    - pkgconfig32(samplerate)
    - pkgconfig32(sndfile)
    - db5-32bit-devel
    - readline-32bit-devel
setup      : |
    %waf_configure --libdir=%libdir% \
                   --systemd-unit \
                   --classic \
                   --mixed \
                   --dbus
build      : |
    %waf_build
install    : |
    %waf_install
    install -Dm00644 $pkgfiles/limits.conf $installdir/etc/security/limits.d/audio.conf
