name       : jack-audio-connection-kit
version    : 1.9.22
release    : 16
source     :
    - https://github.com/jackaudio/jack2/archive/refs/tags/v1.9.22.tar.gz : 1e42b9fc4ad7db7befd414d45ab2f8a159c0b30fcd6eee452be662298766a849
homepage   : https://jackaudio.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.audio
summary    : JACK2 low-latency audio server for multi-core machines.
description: |
    JACK2 is a C++ version of the JACK low-latency audio server for multi-core machines. It is a new implementation of the JACK server core features that aims at removing some limitations of the JACK1 design. The activation system has been changed for a data flow model and lock-free programming techniques for graph access have been used to have a more dynamic and robust system.
emul32     : yes
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(celt)
    - pkgconfig32(dbus-1)
    - pkgconfig32(eigen3)
    - pkgconfig32(expat)
    - pkgconfig32(libgcrypt)
    - pkgconfig32(liblzma)
    - pkgconfig32(libzstd) # remove
    - pkgconfig32(opus)
    - pkgconfig32(portaudio-2.0)
    - pkgconfig32(samplerate)
    - pkgconfig32(sndfile)
    - db5-32bit-devel
    - readline-32bit-devel
setup      : |
    # Fix "Service file '/usr/share//dbus-1/services/org.jackaudio.service.service' is not named after the D-Bus name 'org.jackaudio.service'"
    sed -i 's|org.jackaudio.service|org.jackaudio|g' dbus/org.jackaudio.service.in
    
    %waf_configure --libdir=%libdir% \
                   --systemd-unit \
                   --classic \
                   --mixed \
                   --dbus
build      : |
    %waf_build
install    : |
    %waf_install
    install -Dm00644 $pkgfiles/limits.conf $installdir/etc/security/limits.d/audio.conf
