name       : jack-audio-connection-kit
version    : 0.124.1
release    : 4
source     :
    - http://jackaudio.org/downloads/jack-audio-connection-kit-0.124.1.tar.gz : eb42df6065576f08feeeb60cb9355dce4eb53874534ad71534d7aa31bae561d6
license    :
    - GPL-2.0
    - LGPL-2.1
component  : multimedia.audio
summary    : Jack is a professional sound server daemon.
description: "Jack is a professional sound server daemon that provides real-time,\
    \ low-latency connections for both audio and MIDI data between applications that\
    \ implement its API. \n"
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(celt)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - db5-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/limits.conf $installdir/etc/security/limits.d/50-jack.conf
